*A+



syspag	equ	7

;Experimental values for fattab
fattab	equ	61000	; 63000
wrisec	equ	63968
sector	equ	64960



	ORG	#8000



	DI
	LD	BC,#7FFD
	LD	A,(#5B5C) ; BANKM
;	AND	#FF
	OR	#07
	LD	(#5B5C),A ; BANKM
	OUT	(C),A
	LD	HL,ENDMOV
	LD	DE,#C000
	LD	BC,LENGHC
	LDIR
	LD	BC,#1FFD
	LD	A,(#5B67) ; BANK678
	RES	2,A
	OUT	(C),A
	LD	HL,(#0009)
	SET	2,A
	OUT	(C),A
	LD	BC,#2ADA	; PRESENT IN FIRST +3 ROM
	AND	A
	PUSH	HL
	SBC	HL,BC
	POP	HL
	JR	Z,PLUS3A	; JR IF FIRST +3 ROM DETECTED

	LD	BC,#2C4C	; PRESENT IN +3B ROM ENGLISH VERSION
	AND	A
	PUSH	HL
	SBC	HL,BC
	POP	HL
	JR	Z,PLUS3B	; JR IF +3B ROM ENGLISH VERSION DETECTED

	LD	BC,#2C88	; PRESENT IN +3B ROM SPANISH VERSION
	AND	A
	SBC	HL,BC
	JR	Z,PLUS3S	; JR IF +3B ROM SPANISH VERSION DETECTED

; IF NEITHER VERSION DUNNO WHAT TO DO
; BORDER RED AND LET THE CODE UNMODIFIED

	LD	A,#0A
	OUT	(#FE),A
	JR	PLUS3A

; +3B ROM ENGLISH VERSION ASSUMED

PLUS3B	LD	HL,#104D	; FOR +3B ROM ENGLISH VERSION
	LD	(runexe+1),HL
	LD	HL,#10D4	; FOR +3B ROM ENGLISH VERSION
	LD	(synexe+1),HL
	LD	HL,#26A7	; FOR +3B ROM ENGLISH VERSION
	LD	(SFAIL0+1),HL
	LD	(SFAIL1+1),HL
	LD	(SFAIL2+1),HL
	JR	PLUS3A

; +3B ROM SPANISH VERSION ASSUMED

PLUS3S	LD	HL,#1059	; FOR +3B ROM SPANISH VERSION
	LD	(runexe+1),HL
	LD	HL,#10E0	; FOR +3B ROM SPANISH VERSION
	LD	(synexe+1),HL
	LD	HL,#26B5	; FOR +3B ROM SPANISH VERSION
	LD	(SFAIL0+1),HL
	LD	(SFAIL1+1),HL
	LD	(SFAIL2+1),HL
PLUS3A	CALL	#C000
	LD	BC,#7FFD
	LD	A,(#5B5C) ; BANKM
	AND	#F8
;	OR	#00
	LD	(#5B5C),A ; BANKM
	OUT	(C),A
	EI
	RET

ENDMOV



	ORG	#C000



STARTC

*I B:COMMANDS.GEN
*I B:LOADSYNT.GEN
*I B:MSLOAD.GEN
*I B:MSSAVETA.GEN
*I B:MSCAT5.GEN
*I B:SIMPLECO.GEN
*I B:MSCOPY.GEN
*I B:MSERASE.GEN
*I B:MSFORMAT.GEN
*I B:STANDARD.GEN
*I B:STORAGE.GEN

LENGHC	EQU	$-STARTC

	END
GEN
*I B:MSCOPY.GEN
*I B:MSERASE.GEN
*I B:MSFORMA